### ISSUE TITLE
NormalTangentTest.gltf does not appear as expected

### ISSUE THREAD

**Issue by cx20** [hiloteam/Hilo3d#8]
I tried to display [NormalTangentTest.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/NormalTangentTest) using Hilo3d.
However, it seems to be different from the expected result.

[Hilo3d + NormalTangentTest.gltf result:](https://cx20.github.io/gltf-test/examples/Hilo3d/index.html?category=tutorialModels&model=NormalTangentTest&scale=1&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/32969130-30b1060e-cc27-11e7-80da-6a8982c8d7f4.png)

[Expected result:](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/NormalTangentTest)
![image](https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/NormalTangentTest/screenshot/screenshot.png)

Please see below for the purpose of this test.
https://emackey.github.io/testing-pbr/normal-tangent-readme.html
https://emackey.github.io/testing-pbr/normal-tangent-test.html

/cc @emackey

**Comment by emackey** [comment]
The whole thing is a bit overexposed, but, in the gold column on the right you can see the reflection of the horizon line "spinning around" as the UV map is twisted, which it's not supposed to do.

I've come to recognize this pattern, it's using what Substance Painter calls "DirectX" normals instead of "OpenGL" normals.  Basically the green channel of the tangent-space normal map needs to be inverted by the engine loading the glTF, such that the normal Y vectors go the other way.

**Comment by 06wj** [comment]
The algorithm we used to generate the tangents was reversed, and we fixed the bug in v1.5.7.

**Comment by cx20** [comment]
I confirmed that it was fixed in the latest version (v1.5.7).
https://cx20.github.io/gltf-test/examples/Hilo3d/index.html?category=tutorialModels&model=NormalTangentTest&scale=1&type=glTF
![image](https://user-images.githubusercontent.com/1833979/33017404-90e45908-ce35-11e7-894f-83840d73789f.png)
